spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture
    username: root
    password: SimranGirl1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false # in initial dev, Hibernate ddl-auto update provides seamless schema management

logging:
  level:
    com.furniture.store: DEBUG
    org.springframework.security: INFO
