spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/furniture_store?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false # in initial dev, Hibernate ddl-auto update provides seamless schema management

logging:
  level:
    com.furniture.store: DEBUG
    org.springframework.security: INFO
